---
services: docker

env:
#  - distro: centos7
#  - distro: centos6
#  - distro: fedora27
#  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: ubuntu1204

  # Version 10
  - distro: debian9
    playbook: test-v10.yml
    NODEJS_VERSION: 10
  - distro: debian8
    playbook: test-v10.yml
    NODEJS_VERSION: 10
  - distro: ubuntu1804
    playbook: test-v10.yml
    NODEJS_VERSION: 10
  - distro: ubuntu1604
    playbook: test-v10.yml
    NODEJS_VERSION: 10

  # Version 9
  - distro: debian9
    playbook: test-v9.yml
    NODEJS_VERSION: 9
  - distro: debian8
    playbook: test-v9.yml
    NODEJS_VERSION: 9
  - distro: ubuntu1804
    playbook: test-v9.yml
    NODEJS_VERSION: 9
  - distro: ubuntu1604
    playbook: test-v9.yml
    NODEJS_VERSION: 9

  # Version 8
  - distro: debian9
    playbook: test-v8.yml
    NODEJS_VERSION: 8
  - distro: debian8
    playbook: test-v8.yml
    NODEJS_VERSION: 8
  - distro: ubuntu1804
    playbook: test-v8.yml
    NODEJS_VERSION: 8
  - distro: ubuntu1604
    playbook: test-v8.yml
    NODEJS_VERSION: 8


script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export DOCKER="docker exec --tty ${container_id} env TERM=xterm"

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/tschifftner/4078cf2a8429d967d5e100649ff2caa9/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Make sure correct version is installed
  - ${DOCKER} nodejs --version | grep "${NODEJS_VERSION}"


after_failure:
  - ${DOCKER} nodejs --version
  - ${DOCKER} which nodejs
  - ${DOCKER} complete -p

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
